<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yoobee Lim, Damini Sri Vadrevu">
<meta name="dcterms.date" content="2023-12-17">

<title>Stat 5405 Team Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="profject_files/libs/clipboard/clipboard.min.js"></script>
<script src="profject_files/libs/quarto-html/quarto.js"></script>
<script src="profject_files/libs/quarto-html/popper.min.js"></script>
<script src="profject_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="profject_files/libs/quarto-html/anchor.min.js"></script>
<link href="profject_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="profject_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="profject_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="profject_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="profject_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#pioneering-predictive-analytics-in-prenatal-care" id="toc-pioneering-predictive-analytics-in-prenatal-care" class="nav-link active" data-scroll-target="#pioneering-predictive-analytics-in-prenatal-care">Pioneering Predictive Analytics in Prenatal Care</a>
  <ul class="collapse">
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract">0. Abstract</a></li>
  <li><a href="#dataset-fetal-health" id="toc-dataset-fetal-health" class="nav-link" data-scroll-target="#dataset-fetal-health">1. Dataset: Fetal Health</a>
  <ul class="collapse">
  <li><a href="#load-the-data-and-create-data-visualization" id="toc-load-the-data-and-create-data-visualization" class="nav-link" data-scroll-target="#load-the-data-and-create-data-visualization">1.1 Load the data and create data visualization</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">2. Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#make-binary-response" id="toc-make-binary-response" class="nav-link" data-scroll-target="#make-binary-response">2.1 Make binary response</a></li>
  <li><a href="#training-and-test-data" id="toc-training-and-test-data" class="nav-link" data-scroll-target="#training-and-test-data">2.2 Training and Test Data</a></li>
  <li><a href="#fitting-the-logistic-regression-models" id="toc-fitting-the-logistic-regression-models" class="nav-link" data-scroll-target="#fitting-the-logistic-regression-models">2.3 Fitting the logistic regression models</a></li>
  <li><a href="#evaluating-model-performance-on-test-dataset" id="toc-evaluating-model-performance-on-test-dataset" class="nav-link" data-scroll-target="#evaluating-model-performance-on-test-dataset">2.4 Evaluating model performance on test dataset</a></li>
  </ul></li>
  <li><a href="#cart-algorithm" id="toc-cart-algorithm" class="nav-link" data-scroll-target="#cart-algorithm">3. CART Algorithm</a>
  <ul class="collapse">
  <li><a href="#implement-of-cart-algorithm-and-pruning-the-tree" id="toc-implement-of-cart-algorithm-and-pruning-the-tree" class="nav-link" data-scroll-target="#implement-of-cart-algorithm-and-pruning-the-tree">3.1 Implement of CART algorithm and Pruning the tree</a></li>
  <li><a href="#evaluating-model-performance-on-test-dataset-1" id="toc-evaluating-model-performance-on-test-dataset-1" class="nav-link" data-scroll-target="#evaluating-model-performance-on-test-dataset-1">3.2 Evaluating model performance on test dataset</a></li>
  </ul></li>
  <li><a href="#ordinal-categorical-response-modeling" id="toc-ordinal-categorical-response-modeling" class="nav-link" data-scroll-target="#ordinal-categorical-response-modeling">6. Ordinal Categorical Response Modeling</a>
  <ul class="collapse">
  <li><a href="#reloading-data-and-preparing-training-and-test-data" id="toc-reloading-data-and-preparing-training-and-test-data" class="nav-link" data-scroll-target="#reloading-data-and-preparing-training-and-test-data">6.1 Reloading data and preparing training and test data</a></li>
  <li><a href="#fitting-the-cumulative-logits-models" id="toc-fitting-the-cumulative-logits-models" class="nav-link" data-scroll-target="#fitting-the-cumulative-logits-models">6.2 Fitting the cumulative logits models</a></li>
  <li><a href="#residual-diagnostics" id="toc-residual-diagnostics" class="nav-link" data-scroll-target="#residual-diagnostics">6.3 Residual diagnostics</a></li>
  <li><a href="#evaluating-model-performance-on-test-dataset-2" id="toc-evaluating-model-performance-on-test-dataset-2" class="nav-link" data-scroll-target="#evaluating-model-performance-on-test-dataset-2">6.4 Evaluating model performance on test dataset</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">7. Conclusion</a></li>
  <li><a href="#references-and-citation" id="toc-references-and-citation" class="nav-link" data-scroll-target="#references-and-citation">8. References and Citation</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Stat 5405 Team Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yoobee Lim, Damini Sri Vadrevu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 17, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="pioneering-predictive-analytics-in-prenatal-care" class="level1">
<h1>Pioneering Predictive Analytics in Prenatal Care</h1>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">0. Abstract</h2>
<p>The project aims to evaluate and compare two distinct statistical modeling approaches – ordinal categorical response modeling and binary logit modeling – in the context of predicting fetal health. The ordinal model is chosen for its ability to account for the natural order of the categories in the fetal health data, which includes three levels. Conversely, the binary model simplifies the problem by converting these levels into a binary format (0 and 1), potentially losing some nuanced information but potentially gaining in model simplicity and interpretability. We aim to understand which model provides more accurate and reliable predictions. This comparison will not only help in determining the best approach for this specific dataset but will also contribute to broader knowledge in the field of medical statistics, particularly in prenatal health care.</p>
<p>This proposal outlines a research project aimed at comparing two statistical modeling techniques – ordinal categorical response modeling and binary logit modeling – for classifying fetal health. This comparison is intended to determine which method offers greater accuracy and utility in medical diagnostics, particularly in prenatal care.</p>
</section>
<section id="dataset-fetal-health" class="level2">
<h2 class="anchored" data-anchor-id="dataset-fetal-health">1. Dataset: Fetal Health</h2>
<p>The UN aims to end preventable deaths in newborns and children under 5 by 2030, reducing under-5 mortality to at least 25 per 1,000 live births. Maternal mortality, accounting for 295,000 deaths during and after pregnancy (as of 2017), is predominantly preventable, with 94% occurring in low-resource settings. Cardiotocograms (CTGs) offer a cost-effective means to assess fetal health, aiding in the prevention of child and maternal mortality by monitoring fetal parameters through ultrasound pulses.</p>
<p>Source of the Dataset</p>
<p><a href="https://www.kaggle.com/datasets/andrewmvd/fetal-health-classification/data" class="uri">https://www.kaggle.com/datasets/andrewmvd/fetal-health-classification/data</a></p>
<p>Description of the Dataset</p>
<p>The dataset contains various measurements and indicators relevant to fetal health extracted from Cardiotocogram exams, which were then classified by expert obstetritians into 3 classes. These levels represent different states of fetal well-being and risk:</p>
<ul>
<li><p>Normal (1)</p></li>
<li><p>Suspect (2)</p></li>
<li><p>Pathological (3)</p></li>
</ul>
<p>The dataset for fetal health classification contains the following predictors:</p>
<ul>
<li><p>Baseline Value: Baseline Fetal Heart Rate (FHR)</p></li>
<li><p>Accelerations: Number of accelerations per second</p></li>
<li><p>Fetal Movement: Number of fetal movements per second</p></li>
<li><p>Uterine Contractions: Number of uterine contractions per second</p></li>
<li><p>Light Decelerations: Number of LDs per second</p></li>
<li><p>Severe Decelerations: Number of SDs per second</p></li>
<li><p>Prolongued Decelerations: Number of PDs per second</p></li>
<li><p>Abnormal Short Term Variability: Percentage of time with abnormal short term variability</p></li>
<li><p>Mean Value of Short Term Variability: Mean value of short term variability</p></li>
<li><p>Percentage of Time with Abnormal Long Term Variability: Percentage of time with abnormal long term variability</p></li>
<li><p>Mean Value of Long Term Variability: Mean value of long term variability</p></li>
</ul>
<section id="load-the-data-and-create-data-visualization" class="level3">
<h3 class="anchored" data-anchor-id="load-the-data-and-create-data-visualization">1.1 Load the data and create data visualization</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'fetal_health_short.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Take a look at the graph below, showing our responses for fetal health. A level of 1 means normal, 2 is suspect, and 3 indicates a pathological condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>health_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>fetal_health)</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">barplot</span>(health_counts, <span class="at">col =</span> <span class="st">"lightblue"</span>, <span class="at">main =</span> <span class="st">"Distribution of Fetal Health States"</span>, <span class="at">xlab =</span> <span class="st">"Fetal Health State"</span>, <span class="at">ylab =</span> <span class="st">"Counts"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(health_counts) <span class="sc">+</span> <span class="dv">200</span>))</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="co"># Add numbers on each bar</span></span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">text</span>(<span class="fu">seq_along</span>(health_counts), health_counts, <span class="at">labels =</span> health_counts, <span class="at">pos =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Within the dataset, there are predictors designed for fetal health classification. To gain a comprehensive understanding, we propose a visual inspection through the creation of histograms for each of these predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># Set up the plotting area with multiple panels in one row</span></span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>) <span class="sc">+</span> <span class="fl">0.1</span>)  <span class="co"># Adjust the layout as needed</span></span>
<span id="cb3-3"><a href="#cb3-3"></a></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="co"># Loop through each column and create a histogram</span></span>
<span id="cb3-5"><a href="#cb3-5"></a><span class="cf">for</span> (col <span class="cf">in</span> <span class="fu">colnames</span>(data)) {</span>
<span id="cb3-6"><a href="#cb3-6"></a>  <span class="fu">hist</span>(data[[col]], <span class="at">main =</span> <span class="fu">paste</span>( col), <span class="at">xlab =</span> col, <span class="at">col =</span> <span class="st">"lightblue"</span>, <span class="at">border =</span><span class="st">"white"</span>)</span>
<span id="cb3-7"><a href="#cb3-7"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">2. Logistic Regression</h2>
<p>The binary logistic regression model, a form of generalized linear model (GLIM), is employed to elucidate binary responses.</p>
<p>The data consists of information on n = 2126 fetuses among whom <span class="math inline">\(n_1\)</span> = 1655 exhibit a normal health status, <span class="math inline">\(n_2\)</span> = 295 are classified as suspect, <span class="math inline">\(n_3\)</span> = 176 have pathological condition. The dataset is enriched with 11 potential predictor variables.</p>
<p>Our reasearch questions: Are these variables useful for predicting fetal health(classification)? How well does the binary logit model perform for fetal health classification?</p>
<section id="make-binary-response" class="level3">
<h3 class="anchored" data-anchor-id="make-binary-response">2.1 Make binary response</h3>
<p>Before fitting the model, it is imperative to change the current three-class classification to the binary responses.</p>
<p>In the interest of prioritizing the identification of unhealthy fetuses, we have amalgamated classes 2 (suspect) and 3 (pathological). Our rationale is grounded in the assertion that fetuses falling under either class 2 or 3 are considered unhealthy, aligning with our objective to develop a model adept at predicting unfavorable fetal conditions.</p>
<p>To facilitate the modeling process and emphasize the identification of potentially dangerous statuses, we have transformed the response variable into a binary factor. Herein, we have designated the combined categories of suspect (level 2) and pathological (level 3) as 1 representing poor, while categorizing normal (level 1) as 0. This binary classification allows us to focus on predicting the presence or absence of an poor fetal condition, enhancing the model’s capacity to capture critical health-related nuances.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>data<span class="sc">$</span>fetal_health <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(data<span class="sc">$</span>fetal_health <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb4-2"><a href="#cb4-2"></a></span>
<span id="cb4-3"><a href="#cb4-3"></a>value_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>fetal_health)</span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="fu">print</span>(value_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
1655  471 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>health_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>fetal_health)</span>
<span id="cb6-2"><a href="#cb6-2"></a></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="fu">barplot</span>(health_counts, <span class="at">col =</span> <span class="st">"lightblue"</span>, <span class="at">main =</span> <span class="st">"Fetal Health States"</span>, <span class="at">xlab =</span> <span class="st">"Fetal Health State"</span>, <span class="at">ylab =</span> <span class="st">"counts"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="training-and-test-data" class="level3">
<h3 class="anchored" data-anchor-id="training-and-test-data">2.2 Training and Test Data</h3>
<p>We divide the data into an 80-20 train-test ratio. The train data, which consists of 1700 cases, will be used to train the logit regression model, and the test data, which consists of 426 cases, will be used to verify accuracy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">set.seed</span>(<span class="dv">123457</span>)</span>
<span id="cb7-2"><a href="#cb7-2"></a>train.prop <span class="ot">&lt;-</span> <span class="fl">0.80</span></span>
<span id="cb7-3"><a href="#cb7-3"></a>strats <span class="ot">&lt;-</span> data<span class="sc">$</span>fetal_health</span>
<span id="cb7-4"><a href="#cb7-4"></a>rr <span class="ot">&lt;-</span> <span class="fu">split</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(strats), strats)</span>
<span id="cb7-5"><a href="#cb7-5"></a>idx <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">as.numeric</span>(<span class="fu">unlist</span>(<span class="fu">sapply</span>(rr, <span class="cf">function</span>(x) <span class="fu">sample</span>(x, <span class="fu">length</span>(x)<span class="sc">*</span>train.prop)))))</span>
<span id="cb7-6"><a href="#cb7-6"></a>data.train <span class="ot">&lt;-</span> data[idx, ]</span>
<span id="cb7-7"><a href="#cb7-7"></a>data.test <span class="ot">&lt;-</span> data[<span class="sc">-</span>idx, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In general, it is helpful to check if the train and test data accurately depict the variable distributions and overall data structure. We may check to determine whether the train, test, and total data sets have the same proportions of the two levels of the response.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">table</span>(data.train<span class="sc">$</span>fetal_health)<span class="sc">/</span><span class="fu">nrow</span>(data.train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        0         1 
0.7788235 0.2211765 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">table</span>(data.test<span class="sc">$</span>fetal_health)<span class="sc">/</span><span class="fu">nrow</span>(data.test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        0         1 
0.7769953 0.2230047 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">table</span>(data<span class="sc">$</span>fetal_health)<span class="sc">/</span><span class="fu">nrow</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        0         1 
0.7784572 0.2215428 </code></pre>
</div>
</div>
</section>
<section id="fitting-the-logistic-regression-models" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-logistic-regression-models">2.3 Fitting the logistic regression models</h3>
<p>Fit three models: a full model with all predictors, a null model with only the intercept, and a model employing variable selection. Subsequently, compare the Akaike Information Criterion (AIC) across the models.</p>
<section id="fitting-the-full-model-with-all-predictors" class="level4">
<h4 class="anchored" data-anchor-id="fitting-the-full-model-with-all-predictors">2.3.1 Fitting the full model with all predictors</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>full.logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(fetal_health <span class="sc">~</span> . ,<span class="at">data =</span> data.train, </span>
<span id="cb14-2"><a href="#cb14-2"></a>                  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb14-3"><a href="#cb14-3"></a>summary_result <span class="ot">=</span> <span class="fu">summary</span>(full.logit)</span>
<span id="cb14-4"><a href="#cb14-4"></a>summary_result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fetal_health ~ ., family = binomial(link = "logit"), 
    data = data.train)

Coefficients:
                                                         Estimate Std. Error
(Intercept)                                            -1.687e+01  1.784e+00
baseline.value                                          8.479e-02  1.159e-02
accelerations                                          -5.506e+02  8.605e+01
fetal_movement                                          5.728e+00  2.358e+00
uterine_contractions                                   -2.155e+02  3.692e+01
light_decelerations                                     4.379e+01  5.232e+01
severe_decelerations                                    3.704e+03  1.148e+03
prolongued_decelerations                                2.706e+03  2.574e+02
abnormal_short_term_variability                         7.804e-02  8.730e-03
mean_value_of_short_term_variability                   -1.570e-01  1.831e-01
percentage_of_time_with_abnormal_long_term_variability  3.236e-02  5.868e-03
mean_value_of_long_term_variability                     4.354e-02  2.422e-02
                                                       z value Pr(&gt;|z|)    
(Intercept)                                             -9.456  &lt; 2e-16 ***
baseline.value                                           7.317 2.53e-13 ***
accelerations                                           -6.399 1.57e-10 ***
fetal_movement                                           2.429  0.01512 *  
uterine_contractions                                    -5.837 5.31e-09 ***
light_decelerations                                      0.837  0.40262    
severe_decelerations                                     3.226  0.00125 ** 
prolongued_decelerations                                10.515  &lt; 2e-16 ***
abnormal_short_term_variability                          8.940  &lt; 2e-16 ***
mean_value_of_short_term_variability                    -0.857  0.39136    
percentage_of_time_with_abnormal_long_term_variability   5.514 3.51e-08 ***
mean_value_of_long_term_variability                      1.798  0.07219 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1796.54  on 1699  degrees of freedom
Residual deviance:  692.73  on 1688  degrees of freedom
AIC: 716.73

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>The results shed light on the significance of coefficients in elucidating the fetal health status categorized as poor (1). The model’s predictive performance is evident in the difference between the null deviance (1796.54 on 1699 d.f.) and residual deviance (692.73 on 1688 d.f.), with a larger gap indicating better model fit. The AIC stands at 716.73 for concise evaluation.</p>
</section>
<section id="fitting-the-null-model-with-only-the-intercept" class="level4">
<h4 class="anchored" data-anchor-id="fitting-the-null-model-with-only-the-intercept">2.3.2 Fitting the null model with only the intercept</h4>
<p>The outcomes are displayed below, revealing an AIC of 1798.5, significantly higher than that of the full model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>null.logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(fetal_health <span class="sc">~</span> <span class="dv">1</span> ,<span class="at">data =</span> data.train, </span>
<span id="cb16-2"><a href="#cb16-2"></a>                  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="fu">summary</span>(null.logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fetal_health ~ 1, family = binomial(link = "logit"), 
    data = data.train)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.25882    0.05844  -21.54   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1796.5  on 1699  degrees of freedom
Residual deviance: 1796.5  on 1699  degrees of freedom
AIC: 1798.5

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section>
<section id="fitting-the-model-with-chosen-predictors" class="level4">
<h4 class="anchored" data-anchor-id="fitting-the-model-with-chosen-predictors">2.3.3 Fitting the model with chosen predictors</h4>
<p>We employed both backward and forward selection methods to identify predictors explaining fetal health. Interestingly, the results indicate that using either backward elimination or forward selection alone yields the same outcome as using both methods concurrently.</p>
<p>The results of the fitted model with the selected predictors are presented below. Notably, the AIC is 713.66, slightly smaller than the AIC of the full model, which is 716.73.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>both.logit <span class="ot">&lt;-</span> <span class="fu">step</span>(null.logit, <span class="fu">list</span>(<span class="at">lower=</span><span class="fu">formula</span>(null.logit),</span>
<span id="cb18-2"><a href="#cb18-2"></a>                                    <span class="at">upper=</span><span class="fu">formula</span>(full.logit)),</span>
<span id="cb18-3"><a href="#cb18-3"></a>                   <span class="at">direction=</span><span class="st">"both"</span>,<span class="at">trace=</span><span class="dv">0</span>, <span class="at">data =</span> bank.data.train)</span>
<span id="cb18-4"><a href="#cb18-4"></a></span>
<span id="cb18-5"><a href="#cb18-5"></a><span class="fu">summary</span>(both.logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fetal_health ~ abnormal_short_term_variability + 
    accelerations + prolongued_decelerations + baseline.value + 
    uterine_contractions + percentage_of_time_with_abnormal_long_term_variability + 
    severe_decelerations + fetal_movement + mean_value_of_long_term_variability, 
    family = binomial(link = "logit"), data = data.train)

Coefficients:
                                                         Estimate Std. Error
(Intercept)                                            -1.685e+01  1.744e+00
abnormal_short_term_variability                         7.885e-02  8.640e-03
accelerations                                          -5.657e+02  8.510e+01
prolongued_decelerations                                2.661e+03  2.426e+02
baseline.value                                          8.430e-02  1.151e-02
uterine_contractions                                   -2.173e+02  3.634e+01
percentage_of_time_with_abnormal_long_term_variability  3.184e-02  5.304e-03
severe_decelerations                                    3.763e+03  1.139e+03
fetal_movement                                          5.773e+00  2.362e+00
mean_value_of_long_term_variability                     3.665e-02  2.224e-02
                                                       z value Pr(&gt;|z|)    
(Intercept)                                             -9.659  &lt; 2e-16 ***
abnormal_short_term_variability                          9.127  &lt; 2e-16 ***
accelerations                                           -6.647 2.98e-11 ***
prolongued_decelerations                                10.969  &lt; 2e-16 ***
baseline.value                                           7.323 2.42e-13 ***
uterine_contractions                                    -5.980 2.23e-09 ***
percentage_of_time_with_abnormal_long_term_variability   6.004 1.93e-09 ***
severe_decelerations                                     3.305 0.000949 ***
fetal_movement                                           2.445 0.014498 *  
mean_value_of_long_term_variability                      1.648 0.099409 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1796.54  on 1699  degrees of freedom
Residual deviance:  693.66  on 1690  degrees of freedom
AIC: 713.66

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>AIC comparisons indicate that the full model and the one utilizing both backward and forward selection are similar and superior to the null model. In terms of AIC values, the full model is slightly larger than the model with variable selection, suggesting that the latter performs slightly better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">cat</span>(<span class="st">"Residual diviance:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Residual diviance:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">cat</span>(<span class="st">"null model:"</span>, null.logit<span class="sc">$</span>deviance, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>null model: 1796.536 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">cat</span>(<span class="st">"full model:"</span>, full.logit<span class="sc">$</span>deviance, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>full model: 692.7283 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">cat</span>(<span class="st">"both model:"</span>, both.logit<span class="sc">$</span>deviance, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>both model: 693.6628 </code></pre>
</div>
</div>
<p>However, it’s essential to note that the residual deviance from the full model is the smallest among the three models, making either the full model or the one with variable selection preferable on the training dataset.</p>
</section>
</section>
<section id="evaluating-model-performance-on-test-dataset" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-model-performance-on-test-dataset">2.4 Evaluating model performance on test dataset</h3>
<p>We evaluate how well the models fit the response from the test data. With the merger of suspect and pathological categories, our focus leans towards recall over precision or accuracy, giving priority to sensitivity since prevention is better especially in prenatal healthcare.</p>
<section id="assess-test-data-with-confusion-matrix" class="level4">
<h4 class="anchored" data-anchor-id="assess-test-data-with-confusion-matrix">2.4.1 Assess test data with confusion matrix</h4>
<p>We calculate and compare the confusion matrices, followed by computing recall as percentages for the test data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="co"># Function to calculate precision</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>precision <span class="ot">&lt;-</span> <span class="cf">function</span>(conf_matrix) {</span>
<span id="cb28-3"><a href="#cb28-3"></a>  TP <span class="ot">&lt;-</span> conf_matrix[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb28-4"><a href="#cb28-4"></a>  FP <span class="ot">&lt;-</span> conf_matrix[<span class="dv">1</span>, <span class="dv">2</span>]</span>
<span id="cb28-5"><a href="#cb28-5"></a>  <span class="fu">return</span>(<span class="fu">round</span>((TP <span class="sc">/</span> (TP <span class="sc">+</span> FP))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>))</span>
<span id="cb28-6"><a href="#cb28-6"></a>}</span>
<span id="cb28-7"><a href="#cb28-7"></a><span class="co"># Function to calculate recall</span></span>
<span id="cb28-8"><a href="#cb28-8"></a>recall <span class="ot">&lt;-</span> <span class="cf">function</span>(conf_matrix) {</span>
<span id="cb28-9"><a href="#cb28-9"></a>  TP <span class="ot">&lt;-</span> conf_matrix[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb28-10"><a href="#cb28-10"></a>  FN <span class="ot">&lt;-</span> conf_matrix[<span class="dv">2</span>, <span class="dv">1</span>]</span>
<span id="cb28-11"><a href="#cb28-11"></a>  <span class="fu">return</span>(<span class="fu">round</span>((TP <span class="sc">/</span> (TP <span class="sc">+</span> FN))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>))</span>
<span id="cb28-12"><a href="#cb28-12"></a>}</span>
<span id="cb28-13"><a href="#cb28-13"></a><span class="co"># Function to calculate F1-score</span></span>
<span id="cb28-14"><a href="#cb28-14"></a>f1_score <span class="ot">&lt;-</span> <span class="cf">function</span>(conf_matrix) {</span>
<span id="cb28-15"><a href="#cb28-15"></a>  prec <span class="ot">&lt;-</span> <span class="fu">precision</span>(conf_matrix)</span>
<span id="cb28-16"><a href="#cb28-16"></a>  rec <span class="ot">&lt;-</span> <span class="fu">recall</span>(conf_matrix)</span>
<span id="cb28-17"><a href="#cb28-17"></a>  <span class="fu">return</span>(<span class="fu">round</span>(<span class="dv">2</span> <span class="sc">*</span> (prec <span class="sc">*</span> rec) <span class="sc">/</span> (prec <span class="sc">+</span> rec),<span class="dv">2</span>))</span>
<span id="cb28-18"><a href="#cb28-18"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>pred.full <span class="ot">&lt;-</span> <span class="fu">predict</span>(full.logit, <span class="at">newdata =</span> data.test, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb29-2"><a href="#cb29-2"></a>pred.both <span class="ot">&lt;-</span> <span class="fu">predict</span>(both.logit, <span class="at">newdata =</span> data.test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb29-3"><a href="#cb29-3"></a></span>
<span id="cb29-4"><a href="#cb29-4"></a>(table.full <span class="ot">&lt;-</span> <span class="fu">table</span>(data.test<span class="sc">$</span>fetal_health, pred.full <span class="sc">&gt;</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    FALSE TRUE
  0   314   17
  1    28   67</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>precision_full <span class="ot">&lt;-</span> <span class="fu">precision</span>(table.full)</span>
<span id="cb31-2"><a href="#cb31-2"></a>recall_full <span class="ot">&lt;-</span> <span class="fu">recall</span>(table.full)</span>
<span id="cb31-3"><a href="#cb31-3"></a>f1_score_full <span class="ot">&lt;-</span> <span class="fu">f1_score</span>(table.full)</span>
<span id="cb31-4"><a href="#cb31-4"></a></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="fu">cat</span>(<span class="st">"Full Model Metrics:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Full Model Metrics:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">cat</span>(<span class="st">"accuracy:"</span>, <span class="fu">round</span>((<span class="fu">sum</span>(<span class="fu">diag</span>(table.full))<span class="sc">/</span><span class="fu">sum</span>(table.full))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>),<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>accuracy: 89.44 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="fu">cat</span>(<span class="st">"Precision:"</span>, precision_full,<span class="st">"%"</span>,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Precision: 79.76 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">cat</span>(<span class="st">"Recall:"</span>, recall_full,<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recall: 70.53 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">cat</span>(<span class="st">"F1-Score:"</span>, f1_score_full,<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F1-Score: 74.86 % </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>(table.both <span class="ot">&lt;-</span> <span class="fu">table</span>(data.test<span class="sc">$</span>fetal_health, pred.both <span class="sc">&gt;</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    FALSE TRUE
  0   313   18
  1    27   68</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>precision_both <span class="ot">&lt;-</span> <span class="fu">precision</span>(table.both)</span>
<span id="cb43-2"><a href="#cb43-2"></a>recall_both <span class="ot">&lt;-</span> <span class="fu">recall</span>(table.both)</span>
<span id="cb43-3"><a href="#cb43-3"></a>f1_score_both <span class="ot">&lt;-</span> <span class="fu">f1_score</span>(table.both)</span>
<span id="cb43-4"><a href="#cb43-4"></a></span>
<span id="cb43-5"><a href="#cb43-5"></a><span class="fu">cat</span>(<span class="st">"Both Model Metrics:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Both Model Metrics:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="fu">cat</span>(<span class="st">"accuracy:"</span>, <span class="fu">round</span>((<span class="fu">sum</span>(<span class="fu">diag</span>(table.both))<span class="sc">/</span><span class="fu">sum</span>(table.both))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>),<span class="st">"%"</span> ,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>accuracy: 89.44 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a><span class="fu">cat</span>(<span class="st">"Precision:"</span>, precision_both,<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Precision: 79.07 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a><span class="fu">cat</span>(<span class="st">"Recall:"</span>, recall_both,<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recall: 71.58 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a><span class="fu">cat</span>(<span class="st">"F1-Score:"</span>, f1_score_both,<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F1-Score: 75.14 % </code></pre>
</div>
</div>
<p>As a result, it was found that the recall for the full model is 70.53%, while the both model shows a slight improvement with a recall of 71.58%. This nuanced enhancement leads us to prefer the model utilizing variable selection as our logistic regression model. The recall of <strong>71.58%</strong> suggest that a relatively high percentage of actual positive cases were correctly identified by the models. In general, higher recall percentages indicate better performance in capturing true positives.</p>
<p>Looking ahead, we plan to extend our evaluation by comparing these percentages with other models, including CART, Random Forest, XGBoost, and Ordinal logistic regression. This comparative analysis will provide valuable insights into the relative performance of these models across the dataset.</p>
</section>
<section id="roc-curve" class="level4">
<h4 class="anchored" data-anchor-id="roc-curve">2.4.2 ROC curve</h4>
<p>The ROC curve, a vital metric, assesses prediction accuracy in binary and multi-class classification. It gauges the trade-off between sensitivity (true positive rate) and specificity (false positive rate) in predictions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a>pred.null <span class="ot">&lt;-</span> <span class="fu">predict</span>(null.logit, <span class="at">newdata =</span> data.test, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb53-2"><a href="#cb53-2"></a>pred.full <span class="ot">&lt;-</span> <span class="fu">predict</span>(full.logit, <span class="at">newdata =</span> data.test, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb53-3"><a href="#cb53-3"></a>pred.both <span class="ot">&lt;-</span> <span class="fu">predict</span>(both.logit, <span class="at">newdata =</span> data.test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb53-4"><a href="#cb53-4"></a></span>
<span id="cb53-5"><a href="#cb53-5"></a><span class="fu">library</span>(pROC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Type 'citation("pROC")' for a citation.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'pROC'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    cov, smooth, var</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>roc.null <span class="ot">&lt;-</span> <span class="fu">roc</span>(data.test<span class="sc">$</span>fetal_health, pred.null, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a>auc_null <span class="ot">&lt;-</span> <span class="fu">auc</span>(data.test<span class="sc">$</span>fetal_health, pred.null)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>roc.full <span class="ot">&lt;-</span> <span class="fu">roc</span>(data.test<span class="sc">$</span>fetal_health, pred.full, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &gt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a>auc_full <span class="ot">&lt;-</span> <span class="fu">auc</span>(data.test<span class="sc">$</span>fetal_health, pred.full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1
Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a>roc.both <span class="ot">&lt;-</span> <span class="fu">roc</span>(data.test<span class="sc">$</span>fetal_health, pred.both, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &gt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a>auc_both <span class="ot">&lt;-</span> <span class="fu">auc</span>(data.test<span class="sc">$</span>fetal_health, pred.both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1
Setting direction: controls &lt; cases</code></pre>
</div>
</div>
<p>The AUC (area under the curve) for the test data is almost identical in both models, full and both.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb70-2"><a href="#cb70-2"></a><span class="fu">plot</span>(roc.null, <span class="at">main =</span> <span class="st">"ROC Curve - Null Model"</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb70-3"><a href="#cb70-3"></a><span class="fu">text</span>(<span class="fl">0.8</span>, <span class="fl">0.2</span>, <span class="fu">paste</span>(<span class="st">"AUC ="</span>, <span class="fu">round</span>(auc_null, <span class="dv">2</span>)), <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb70-4"><a href="#cb70-4"></a></span>
<span id="cb70-5"><a href="#cb70-5"></a><span class="fu">plot</span>(roc.full, <span class="at">main =</span> <span class="st">"ROC Curve - Full Model"</span>, <span class="at">col =</span> <span class="st">"green"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb70-6"><a href="#cb70-6"></a><span class="fu">text</span>(<span class="fl">0.8</span>, <span class="fl">0.2</span>, <span class="fu">paste</span>(<span class="st">"AUC ="</span>, <span class="fu">round</span>(auc_full, <span class="dv">2</span>)), <span class="at">col =</span> <span class="st">"green"</span>)</span>
<span id="cb70-7"><a href="#cb70-7"></a></span>
<span id="cb70-8"><a href="#cb70-8"></a><span class="fu">plot</span>(roc.both, <span class="at">main =</span> <span class="st">"ROC Curve - Both Model"</span>, <span class="at">col =</span> <span class="st">"purple"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb70-9"><a href="#cb70-9"></a><span class="fu">text</span>(<span class="fl">0.8</span>, <span class="fl">0.2</span>, <span class="fu">paste</span>(<span class="st">"AUC ="</span>, <span class="fu">round</span>(auc_both, <span class="dv">2</span>)), <span class="at">col =</span> <span class="st">"purple"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="cart-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="cart-algorithm">3. CART Algorithm</h2>
<p>Classification and Regression Tree(CART) algorithm systematically partitions the dataset based on predictor variables to construct a decision tree. This tree serves as a predictive model that can be used for classification or regression tasks.</p>
<section id="implement-of-cart-algorithm-and-pruning-the-tree" class="level3">
<h3 class="anchored" data-anchor-id="implement-of-cart-algorithm-and-pruning-the-tree">3.1 Implement of CART algorithm and Pruning the tree</h3>
<p>Initially, the CART algorithm is employed to grow the tree using all predictors. The subsequent step involves pruning the tree by selecting the optimal complexity parameter (CP) based on minimizing cross-validated prediction error (xerror).</p>
<section id="implement-the-cart-algorithm" class="level4">
<h4 class="anchored" data-anchor-id="implement-the-cart-algorithm">3.1.1 Implement the CART algorithm</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb71-2"><a href="#cb71-2"></a></span>
<span id="cb71-3"><a href="#cb71-3"></a>fit.allp <span class="ot">&lt;-</span> <span class="fu">rpart</span>(fetal_health <span class="sc">~</span>., <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">data =</span> data.train,</span>
<span id="cb71-4"><a href="#cb71-4"></a>                  <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">minsplit =</span> <span class="dv">1</span>, <span class="at">cp =</span> <span class="fl">0.001</span>))</span>
<span id="cb71-5"><a href="#cb71-5"></a><span class="fu">printcp</span>(fit.allp) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = fetal_health ~ ., data = data.train, method = "class", 
    control = rpart.control(minsplit = 1, cp = 0.001))

Variables actually used in tree construction:
 [1] abnormal_short_term_variability                       
 [2] accelerations                                         
 [3] baseline.value                                        
 [4] fetal_movement                                        
 [5] light_decelerations                                   
 [6] mean_value_of_long_term_variability                   
 [7] mean_value_of_short_term_variability                  
 [8] percentage_of_time_with_abnormal_long_term_variability
 [9] prolongued_decelerations                              
[10] uterine_contractions                                  

Root node error: 376/1700 = 0.22118

n= 1700 

          CP nsplit rel error  xerror     xstd
1  0.3563830      0  1.000000 1.00000 0.045512
2  0.1489362      1  0.643617 0.76064 0.041020
3  0.0904255      2  0.494681 0.49468 0.034230
4  0.0186170      3  0.404255 0.40691 0.031382
5  0.0159574      5  0.367021 0.40957 0.031474
6  0.0106383      7  0.335106 0.38298 0.030533
7  0.0093085      8  0.324468 0.35904 0.029649
8  0.0079787     10  0.305851 0.34574 0.029141
9  0.0053191     12  0.289894 0.34574 0.029141
10 0.0039894     34  0.156915 0.34574 0.029141
11 0.0026596     38  0.140957 0.37234 0.030145
12 0.0019947     60  0.082447 0.35372 0.029447
13 0.0017730     69  0.061170 0.35638 0.029549
14 0.0013298     72  0.055851 0.36702 0.029948
15 0.0010000     96  0.023936 0.37766 0.030340</code></pre>
</div>
</div>
<p>The least cross-validated prediction error (xerror) is shown below along with the corresponding complexity parameter (CP).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1"></a>xerr <span class="ot">=</span> fit.allp<span class="sc">$</span>cptable[<span class="fu">which.min</span>(fit.allp<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"xerror"</span>]</span>
<span id="cb73-2"><a href="#cb73-2"></a>cp<span class="ot">=</span> fit.allp<span class="sc">$</span>cptable[<span class="fu">which.min</span>(fit.allp<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb73-3"><a href="#cb73-3"></a></span>
<span id="cb73-4"><a href="#cb73-4"></a><span class="fu">cat</span>(<span class="st">"Smallest xerror:"</span>,xerr, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Smallest xerror: 0.3457447 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1"></a><span class="fu">cat</span>(<span class="st">"corresponding CP:"</span>,cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>corresponding CP: 0.007978723</code></pre>
</div>
</div>
</section>
<section id="visualizing-cross-validation-results-and-fitted-tree" class="level4">
<h4 class="anchored" data-anchor-id="visualizing-cross-validation-results-and-fitted-tree">3.1.2 Visualizing cross-validation results and fitted tree</h4>
<p>This section showcases a plotted representation of cross-validation results, aiding in the identification of the optimal complexity parameter for minimal prediction errors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1"></a><span class="fu">plotcp</span>(fit.allp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Additionally, we can generate an attractive plot of the fitted tree, characterized by a substantial number of leaf nodes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb78-2"><a href="#cb78-2"></a><span class="fu">rpart.plot</span>(fit.allp, <span class="at">extra =</span> <span class="st">"auto"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: labs do not fit even at cex 0.15, there may be some overplotting</code></pre>
</div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="tree-pruning" class="level4">
<h4 class="anchored" data-anchor-id="tree-pruning">3.1.3 Tree pruning</h4>
<p>In this stage, we proceed with pruning the tree, utilizing the optimal complexity parameter (CP) obtained from the cross-validation results. The aim is to prune the tree with the best CP, specifically using fit.allp, to prevent overfitting. This involves selecting a tree size that minimizes the cross-validation error (xerror), favoring shallower trees over deeper ones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1"></a>pfit.allp <span class="ot">&lt;-</span> <span class="fu">prune</span>(fit.allp, <span class="at">cp =</span></span>
<span id="cb80-2"><a href="#cb80-2"></a>    fit.allp<span class="sc">$</span>cptable[<span class="fu">which.min</span>(fit.allp<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>])</span>
<span id="cb80-3"><a href="#cb80-3"></a><span class="fu">rpart.plot</span>(pfit.allp, <span class="at">extra =</span> <span class="st">"auto"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="evaluating-model-performance-on-test-dataset-1" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-model-performance-on-test-dataset-1">3.2 Evaluating model performance on test dataset</h3>
<p>In this section, we assess the model’s performance using the test dataset. The evaluation includes calculating confusion matrices for test data predictions and computing key metrics such as accuracy, precision, recall (sensitivity or true positive rate), F1-score, specificity (true negative rate), and the misclassification error rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1"></a>test_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">actual =</span> data.test<span class="sc">$</span>fetal_health, <span class="at">pred =</span> <span class="cn">NA</span>)</span>
<span id="cb81-2"><a href="#cb81-2"></a>test_df<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(pfit.allp, <span class="at">newdata =</span> data.test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb81-3"><a href="#cb81-3"></a>(conf_matrix_base <span class="ot">&lt;-</span> <span class="fu">table</span>(test_df<span class="sc">$</span>actual, test_df<span class="sc">$</span>pred)) <span class="co">#confusion matrix</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      0   1
  0 322   9
  1  24  71</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1"></a>accuracy_tree <span class="ot">&lt;-</span> <span class="fu">round</span>((<span class="fu">sum</span>(<span class="fu">diag</span>(conf_matrix_base))<span class="sc">/</span><span class="fu">sum</span>(conf_matrix_base))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span>
<span id="cb83-2"><a href="#cb83-2"></a></span>
<span id="cb83-3"><a href="#cb83-3"></a><span class="co"># Assuming 'conf_matrix_base' is your confusion matrix</span></span>
<span id="cb83-4"><a href="#cb83-4"></a>TP <span class="ot">&lt;-</span> conf_matrix_base[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb83-5"><a href="#cb83-5"></a>TN <span class="ot">&lt;-</span> conf_matrix_base[<span class="dv">1</span>, <span class="dv">1</span>]</span>
<span id="cb83-6"><a href="#cb83-6"></a>FP <span class="ot">&lt;-</span> conf_matrix_base[<span class="dv">1</span>, <span class="dv">2</span>]</span>
<span id="cb83-7"><a href="#cb83-7"></a>FN <span class="ot">&lt;-</span> conf_matrix_base[<span class="dv">2</span>, <span class="dv">1</span>]</span>
<span id="cb83-8"><a href="#cb83-8"></a></span>
<span id="cb83-9"><a href="#cb83-9"></a><span class="co"># Precision</span></span>
<span id="cb83-10"><a href="#cb83-10"></a>precision <span class="ot">&lt;-</span> <span class="fu">round</span>((TP <span class="sc">/</span> (TP <span class="sc">+</span> FP))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span>
<span id="cb83-11"><a href="#cb83-11"></a></span>
<span id="cb83-12"><a href="#cb83-12"></a><span class="co"># Recall (Sensitivity)</span></span>
<span id="cb83-13"><a href="#cb83-13"></a>recall <span class="ot">&lt;-</span> <span class="fu">round</span>((TP <span class="sc">/</span> (TP <span class="sc">+</span> FN))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span>
<span id="cb83-14"><a href="#cb83-14"></a></span>
<span id="cb83-15"><a href="#cb83-15"></a>specificity <span class="ot">&lt;-</span> <span class="fu">round</span>((TN<span class="sc">/</span>(TN <span class="sc">+</span>FP))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span>
<span id="cb83-16"><a href="#cb83-16"></a></span>
<span id="cb83-17"><a href="#cb83-17"></a><span class="co"># F1-score</span></span>
<span id="cb83-18"><a href="#cb83-18"></a>f1_score <span class="ot">&lt;-</span> <span class="fu">round</span>((<span class="dv">2</span> <span class="sc">*</span> (precision <span class="sc">*</span> recall) <span class="sc">/</span> (precision <span class="sc">+</span> recall)),<span class="dv">2</span>)</span>
<span id="cb83-19"><a href="#cb83-19"></a></span>
<span id="cb83-20"><a href="#cb83-20"></a><span class="fu">cat</span>(<span class="st">"accuracy:"</span>, accuracy_tree,<span class="st">"%"</span>, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>accuracy: 92.25 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1"></a><span class="fu">cat</span>(<span class="st">"Precision:"</span>, precision,<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Precision: 88.75 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1"></a><span class="fu">cat</span>(<span class="st">"Recall:"</span>, recall,<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recall: 74.74 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1"></a><span class="fu">cat</span>(<span class="st">"F1-Score:"</span>, f1_score,<span class="st">"%"</span> , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F1-Score: 81.14 % </code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1"></a><span class="fu">cat</span>(<span class="st">"specificity:"</span>, specificity,<span class="st">"%"</span>, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>specificity: 97.28 % </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1"></a>mis.rate <span class="ot">&lt;-</span> (conf_matrix_base[<span class="dv">1</span>, <span class="dv">2</span>] <span class="sc">+</span> conf_matrix_base[<span class="dv">2</span>, <span class="dv">1</span>])<span class="sc">/</span><span class="fu">sum</span>(conf_matrix_base)</span>
<span id="cb93-2"><a href="#cb93-2"></a><span class="fu">cat</span>(<span class="st">"misclassification error rate:"</span>,<span class="fu">round</span>((mis.rate)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>),<span class="st">"%"</span>, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>misclassification error rate: 7.75 % </code></pre>
</div>
</div>
<p>As highlighted earlier, our primary focus is on the recall score. The evaluation revealed a commendable recall of 74.74% for the pruned tree, signifying its effectiveness in identifying approximately three-quarters of the actual positive cases and minimizing missed instances.</p>
<p>In comparison with the logistic regression model, the pruned tree from the CART algorithm demonstrates better performance with a higher recall of 74.74%, surpassing the logistic regression model’s 71.58%. Looking forward, we’ll continue these comparisons with upcoming models, including Random Forest, XGBoost, and Ordinal logistic regression.</p>
</section>
</section>
<section id="ordinal-categorical-response-modeling" class="level2">
<h2 class="anchored" data-anchor-id="ordinal-categorical-response-modeling">6. Ordinal Categorical Response Modeling</h2>
<p>Initially, our response variables consist of three classes, necessitating models designed for categorical responses with more than two levels. In this context, our responses are ordinal, signifying distinct states of fetal well-being and associated risks graded from 1 to 3 (indicating levels of danger). When dealing with an ordinal response variable, modeling cumulative logits is an effective approach.</p>
<p>Our research questions: Are these variables explain fetal health? How well does cumulative logits model perform in classifying ordinal categorical responses for fetal health?</p>
<section id="reloading-data-and-preparing-training-and-test-data" class="level3">
<h3 class="anchored" data-anchor-id="reloading-data-and-preparing-training-and-test-data">6.1 Reloading data and preparing training and test data</h3>
<p>In this step, we reload the data and prepare it for training and testing. At first, we converted responses to binary factors for binary classification, necessitating the reloading of data to reintroduce the original 3-class response.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1"></a>ord <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'fetal_health_short.csv'</span>)</span>
<span id="cb95-2"><a href="#cb95-2"></a><span class="co">#colnames(ord)[colnames(ord) == "baseline.value"] &lt;- "baseline_value"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1"></a><span class="fu">table</span>(ord<span class="sc">$</span>fetal_health)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3 
1655  295  176 </code></pre>
</div>
</div>
<p>We perform an 80-20 split of the data, creating separate training and test sets. Subsequently, we verify whether the proportions of the three response levels are consistent across the train, test, and overall datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1"></a><span class="co"># Do 80-20 glass.train-glass.test split of the data dat - random split</span></span>
<span id="cb98-2"><a href="#cb98-2"></a><span class="fu">set.seed</span>(<span class="dv">123457</span>)</span>
<span id="cb98-3"><a href="#cb98-3"></a>strats <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(ord<span class="sc">$</span>fetal_health)</span>
<span id="cb98-4"><a href="#cb98-4"></a>rr <span class="ot">&lt;-</span> <span class="fu">split</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(strats),strats)</span>
<span id="cb98-5"><a href="#cb98-5"></a>p<span class="ot">&lt;-</span> <span class="fl">0.8</span></span>
<span id="cb98-6"><a href="#cb98-6"></a>idx <span class="ot">&lt;-</span> </span>
<span id="cb98-7"><a href="#cb98-7"></a>  <span class="fu">sort</span>(<span class="fu">as.numeric</span>(<span class="fu">unlist</span>(<span class="fu">sapply</span>(rr, <span class="cf">function</span>(x) <span class="fu">sample</span>(x, <span class="fu">length</span>(x) <span class="sc">*</span> p)))))</span>
<span id="cb98-8"><a href="#cb98-8"></a>ord.train <span class="ot">&lt;-</span> ord[idx,]</span>
<span id="cb98-9"><a href="#cb98-9"></a><span class="fu">table</span>(ord.train<span class="sc">$</span>fetal_health)<span class="sc">/</span><span class="fu">nrow</span>(ord.train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         1          2          3 
0.77882353 0.13882353 0.08235294 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1"></a>ord.test <span class="ot">&lt;-</span> ord[<span class="sc">-</span>idx,]</span>
<span id="cb100-2"><a href="#cb100-2"></a><span class="fu">table</span>(ord.test<span class="sc">$</span>fetal_health)<span class="sc">/</span><span class="fu">nrow</span>(ord.test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         1          2          3 
0.77699531 0.13849765 0.08450704 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1"></a><span class="fu">table</span>(ord<span class="sc">$</span>fetal_health)<span class="sc">/</span><span class="fu">nrow</span>(ord)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         1          2          3 
0.77845720 0.13875823 0.08278457 </code></pre>
</div>
</div>
</section>
<section id="fitting-the-cumulative-logits-models" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-cumulative-logits-models">6.2 Fitting the cumulative logits models</h3>
<p>Fit three models: a full model with all predictors, a null model with only the intercept, and a model employing variable selection.</p>
<section id="fitting-the-full-model-with-all-predictors-1" class="level4">
<h4 class="anchored" data-anchor-id="fitting-the-full-model-with-all-predictors-1">6.2.1 Fitting the full model with all predictors</h4>
<p>Below, you’ll find the code and output detailing the fitting of the full model with all predictors. It’s important to note that the polr() function, unfortunately, does not furnish p-values for each coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1"></a><span class="fu">library</span>(MASS) </span>
<span id="cb104-2"><a href="#cb104-2"></a>ord.full <span class="ot">&lt;-</span> <span class="fu">polr</span>(<span class="fu">as.factor</span>(fetal_health) <span class="sc">~</span> ., <span class="at">data =</span> ord.train)</span>
<span id="cb104-3"><a href="#cb104-3"></a><span class="fu">summary</span>(ord.full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = as.factor(fetal_health) ~ ., data = ord.train)

Coefficients:
                                                            Value Std. Error
baseline.value                                            0.03878  0.0091726
accelerations                                          -543.43946  0.0060758
fetal_movement                                            5.03533  1.7673494
uterine_contractions                                   -152.92556  0.0166025
light_decelerations                                     100.36722  0.0062741
severe_decelerations                                   3691.07534  0.0003749
prolongued_decelerations                               2598.86141  0.0035972
abnormal_short_term_variability                           0.07947  0.0076907
mean_value_of_short_term_variability                      0.09905  0.1173463
percentage_of_time_with_abnormal_long_term_variability    0.03726  0.0044032
mean_value_of_long_term_variability                       0.02634  0.0195759
                                                          t value
baseline.value                                          4.227e+00
accelerations                                          -8.944e+04
fetal_movement                                          2.849e+00
uterine_contractions                                   -9.211e+03
light_decelerations                                     1.600e+04
severe_decelerations                                    9.847e+06
prolongued_decelerations                                7.225e+05
abnormal_short_term_variability                         1.033e+01
mean_value_of_short_term_variability                    8.441e-01
percentage_of_time_with_abnormal_long_term_variability  8.463e+00
mean_value_of_long_term_variability                     1.345e+00

Intercepts:
    Value        Std. Error   t value     
1|2      11.1612       1.3483       8.2781
2|3      13.8827       1.3633      10.1829

Residual Deviance: 1049.311 
AIC: 1075.311 </code></pre>
</div>
</div>
<p>To address this limitation, the following code demonstrates how we can calculate the p-values and incorporate them into the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1"></a>ctable1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(ord.full))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(ctable1[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb109-2"><a href="#cb109-2"></a>(ctable1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ctable1, <span class="st">"p value"</span> <span class="ot">=</span> p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                               Value
baseline.value                                            0.03877593
accelerations                                          -543.43946331
fetal_movement                                            5.03533477
uterine_contractions                                   -152.92555528
light_decelerations                                     100.36722416
severe_decelerations                                   3691.07534010
prolongued_decelerations                               2598.86141478
abnormal_short_term_variability                           0.07946720
mean_value_of_short_term_variability                      0.09904799
percentage_of_time_with_abnormal_long_term_variability    0.03726431
mean_value_of_long_term_variability                       0.02633634
1|2                                                      11.16122571
2|3                                                      13.88268650
                                                         Std. Error
baseline.value                                         0.0091726378
accelerations                                          0.0060758137
fetal_movement                                         1.7673494137
uterine_contractions                                   0.0166024907
light_decelerations                                    0.0062741098
severe_decelerations                                   0.0003748579
prolongued_decelerations                               0.0035971757
abnormal_short_term_variability                        0.0076906858
mean_value_of_short_term_variability                   0.1173462768
percentage_of_time_with_abnormal_long_term_variability 0.0044031889
mean_value_of_long_term_variability                    0.0195759304
1|2                                                    1.3482760690
2|3                                                    1.3633347360
                                                             t value
baseline.value                                          4.227348e+00
accelerations                                          -8.944308e+04
fetal_movement                                          2.849088e+00
uterine_contractions                                   -9.211001e+03
light_decelerations                                     1.599705e+04
severe_decelerations                                    9.846598e+06
prolongued_decelerations                                7.224727e+05
abnormal_short_term_variability                         1.033291e+01
mean_value_of_short_term_variability                    8.440659e-01
percentage_of_time_with_abnormal_long_term_variability  8.463029e+00
mean_value_of_long_term_variability                     1.345343e+00
1|2                                                     8.278146e+00
2|3                                                     1.018289e+01
                                                            p value
baseline.value                                         2.364617e-05
accelerations                                          0.000000e+00
fetal_movement                                         4.384469e-03
uterine_contractions                                   0.000000e+00
light_decelerations                                    0.000000e+00
severe_decelerations                                   0.000000e+00
prolongued_decelerations                               0.000000e+00
abnormal_short_term_variability                        5.001716e-25
mean_value_of_short_term_variability                   3.986326e-01
percentage_of_time_with_abnormal_long_term_variability 2.605216e-17
mean_value_of_long_term_variability                    1.785145e-01
1|2                                                    1.251081e-16
2|3                                                    2.364353e-24</code></pre>
</div>
</div>
<p>From the coefficients, we can easily compute the odds ratios as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(ord.full))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                        baseline.value 
                                          1.039538e+00 
                                         accelerations 
                                         9.710461e-237 
                                        fetal_movement 
                                          1.537511e+02 
                                  uterine_contractions 
                                          3.848356e-67 
                                   light_decelerations 
                                          3.880893e+43 
                                  severe_decelerations 
                                                   Inf 
                              prolongued_decelerations 
                                                   Inf 
                       abnormal_short_term_variability 
                                          1.082710e+00 
                  mean_value_of_short_term_variability 
                                          1.104119e+00 
percentage_of_time_with_abnormal_long_term_variability 
                                          1.037967e+00 
                   mean_value_of_long_term_variability 
                                          1.026686e+00 </code></pre>
</div>
</div>
<p>The majority of coefficients are small, indicating that the examined features have limited influence on the occurrence of the event. Notably, severe_decelerations and prolongued_decelerations exhibit “Inf” odds ratios, suggesting an infinite positive association with the event. However, it’s crucial to acknowledge that an odds ratio of “Inf” may signify perfect separation, necessitating caution in interpretation and recognizing potential challenges within the model.</p>
</section>
<section id="fitting-the-null-model-with-intercepts-only" class="level4">
<h4 class="anchored" data-anchor-id="fitting-the-null-model-with-intercepts-only">6.2.2 Fitting the null model with intercepts only</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1"></a>ord.null <span class="ot">&lt;-</span> <span class="fu">polr</span>(<span class="fu">as.factor</span>(fetal_health)<span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>ord.train)</span>
<span id="cb113-2"><a href="#cb113-2"></a><span class="fu">summary</span>(ord.null)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = as.factor(fetal_health) ~ 1, data = ord.train)

No coefficients

Intercepts:
    Value   Std. Error t value
1|2  1.2588  0.0584    21.5416
2|3  2.4108  0.0882    27.3252

Residual Deviance: 2292.999 
AIC: 2296.999 </code></pre>
</div>
</div>
<p>Calculate the p-values and incorporate them with table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1"></a>ctable2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(ord.null))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(ctable2[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb118-2"><a href="#cb118-2"></a>(ctable2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ctable2, <span class="st">"p value"</span> <span class="ot">=</span> p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Value Std. Error  t value       p value
1|2 1.258824 0.05843682 21.54162 6.344410e-103
2|3 2.410799 0.08822632 27.32517 2.130885e-164</code></pre>
</div>
</div>
</section>
<section id="fitting-the-model-with-selected-predictors" class="level4">
<h4 class="anchored" data-anchor-id="fitting-the-model-with-selected-predictors">6.2.3 Fitting the model with selected predictors</h4>
<p>For enhanced model efficiency, we employ variable selection through a stepwise procedure, utilizing the smallest Akaike Information Criterion (AIC) as the criterion for selection. This approach helps streamline the model by identifying and incorporating the most influential predictors, contributing to a more concise and effective model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1"></a>vs.s <span class="ot">&lt;-</span> <span class="fu">polr</span>(<span class="fu">as.factor</span>(fetal_health)<span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>ord.train)</span>
<span id="cb120-2"><a href="#cb120-2"></a>ord.step <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(vs.s, <span class="at">scope =</span> <span class="sc">~</span>baseline.value <span class="sc">+</span> accelerations <span class="sc">+</span> fetal_movement <span class="sc">+</span> uterine_contractions <span class="sc">+</span> light_decelerations <span class="sc">+</span> severe_decelerations <span class="sc">+</span> prolongued_decelerations <span class="sc">+</span> abnormal_short_term_variability <span class="sc">+</span> mean_value_of_short_term_variability <span class="sc">+</span> percentage_of_time_with_abnormal_long_term_variability <span class="sc">+</span> mean_value_of_long_term_variability, <span class="at">trace=</span><span class="cn">FALSE</span>,</span>
<span id="cb120-3"><a href="#cb120-3"></a>             <span class="at">direction =</span> <span class="st">"both"</span>)</span>
<span id="cb120-4"><a href="#cb120-4"></a></span>
<span id="cb120-5"><a href="#cb120-5"></a><span class="fu">summary</span>(ord.step)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = as.factor(fetal_health) ~ abnormal_short_term_variability + 
    prolongued_decelerations + accelerations + percentage_of_time_with_abnormal_long_term_variability + 
    severe_decelerations + uterine_contractions + baseline.value + 
    light_decelerations + fetal_movement + mean_value_of_long_term_variability, 
    data = ord.train)

Coefficients:
                                                            Value Std. Error
abnormal_short_term_variability                           0.07753  0.0071849
prolongued_decelerations                               2557.32171  0.0040825
accelerations                                          -550.14473  0.0061169
percentage_of_time_with_abnormal_long_term_variability    0.03617  0.0038252
severe_decelerations                                   3705.68261  0.0003529
uterine_contractions                                   -146.50102  0.0176435
baseline.value                                            0.03815  0.0091041
light_decelerations                                     114.45415  0.0143483
fetal_movement                                            5.27349  1.7488002
mean_value_of_long_term_variability                       0.02454  0.0191190
                                                          t value
abnormal_short_term_variability                         1.079e+01
prolongued_decelerations                                6.264e+05
accelerations                                          -8.994e+04
percentage_of_time_with_abnormal_long_term_variability  9.455e+00
severe_decelerations                                    1.050e+07
uterine_contractions                                   -8.303e+03
baseline.value                                          4.191e+00
light_decelerations                                     7.977e+03
fetal_movement                                          3.015e+00
mean_value_of_long_term_variability                     1.284e+00

Intercepts:
    Value         Std. Error    t value      
1|2       10.8695        1.2581        8.6397
2|3       13.5600        1.2638       10.7299

Residual Deviance: 1050.209 
AIC: 1074.209 </code></pre>
</div>
</div>
<p>Calculate the p-values and incorporate them with table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1"></a>ctable3 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(ord.step))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(ctable3[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb125-2"><a href="#cb125-2"></a>(ctable3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ctable3, <span class="st">"p value"</span> <span class="ot">=</span> p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                               Value
abnormal_short_term_variability                           0.07753110
prolongued_decelerations                               2557.32170742
accelerations                                          -550.14473456
percentage_of_time_with_abnormal_long_term_variability    0.03616806
severe_decelerations                                   3705.68260541
uterine_contractions                                   -146.50101822
baseline.value                                            0.03815299
light_decelerations                                     114.45414538
fetal_movement                                            5.27348995
mean_value_of_long_term_variability                       0.02454166
1|2                                                      10.86945820
2|3                                                      13.55997995
                                                         Std. Error
abnormal_short_term_variability                        0.0071848961
prolongued_decelerations                               0.0040825055
accelerations                                          0.0061169292
percentage_of_time_with_abnormal_long_term_variability 0.0038251789
severe_decelerations                                   0.0003528711
uterine_contractions                                   0.0176434897
baseline.value                                         0.0091040791
light_decelerations                                    0.0143482809
fetal_movement                                         1.7488002263
mean_value_of_long_term_variability                    0.0191190405
1|2                                                    1.2580800883
2|3                                                    1.2637563248
                                                             t value
abnormal_short_term_variability                         1.079084e+01
prolongued_decelerations                                6.264099e+05
accelerations                                          -8.993806e+04
percentage_of_time_with_abnormal_long_term_variability  9.455261e+00
severe_decelerations                                    1.050152e+07
uterine_contractions                                   -8.303404e+03
baseline.value                                          4.190758e+00
light_decelerations                                     7.976854e+03
fetal_movement                                          3.015490e+00
mean_value_of_long_term_variability                     1.283624e+00
1|2                                                     8.639719e+00
2|3                                                     1.072990e+01
                                                            p value
abnormal_short_term_variability                        3.802781e-27
prolongued_decelerations                               0.000000e+00
accelerations                                          0.000000e+00
percentage_of_time_with_abnormal_long_term_variability 3.222171e-21
severe_decelerations                                   0.000000e+00
uterine_contractions                                   0.000000e+00
baseline.value                                         2.780245e-05
light_decelerations                                    0.000000e+00
fetal_movement                                         2.565642e-03
mean_value_of_long_term_variability                    1.992736e-01
1|2                                                    5.635154e-18
2|3                                                    7.367525e-27</code></pre>
</div>
</div>
</section>
</section>
<section id="residual-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="residual-diagnostics">6.3 Residual diagnostics</h3>
<section id="normal-q-q-plot" class="level4">
<h4 class="anchored" data-anchor-id="normal-q-q-plot">6.3.1 Normal Q-Q Plot</h4>
<p>The code assists in residual diagnostics, examining differences between observed and predicted values. The normal Q-Q plot, featuring a straight line for an approximate normal distribution, is crucial for validating assumptions, identifying outliers, and bolstering the reliability of statistical inferences from the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1"></a><span class="fu">library</span>(sure) </span>
<span id="cb127-2"><a href="#cb127-2"></a><span class="co">#Normal Q-Q plot of PO model residuals.</span></span>
<span id="cb127-3"><a href="#cb127-3"></a><span class="fu">autoplot.polr</span>(ord.full) <span class="co">#q-q plot of residuals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="goodness-of-fitgof-plot-for-residual-assessment" class="level4">
<h4 class="anchored" data-anchor-id="goodness-of-fitgof-plot-for-residual-assessment">6.3.2 Goodness-of-Fit(GoF) Plot for residual assessment</h4>
<p>The GoF plot gauges how well the model’s residuals match the expected distribution. When the empirical Cumulative Distribution Function (CDF) line aligns with simulated lines within confidence bands, it confirms a robust fit, bolstering confidence in the model’s ability to capture underlying data patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1"></a><span class="co">#Empirical c.d.f. of PO model residuals.</span></span>
<span id="cb128-2"><a href="#cb128-2"></a><span class="fu">plot</span>(<span class="fu">gof</span>(ord.full, <span class="at">nsim =</span> <span class="dv">50</span>))  <span class="co">#gof plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="profject_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="evaluating-model-performance-on-test-dataset-2" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-model-performance-on-test-dataset-2">6.4 Evaluating model performance on test dataset</h3>
<p>We employ the optimized model selected through a stepwise procedure, prioritizing the smallest AIC as the criterion. Thus, we can evaluate model performance using the model fitted with selected variables.<br>
This evaluation encompasses the calculation of confusion matrices for test data predictions, along with the computation of key metrics such as precision, recall, and F1-score for each classification. Additionally, accuracy is determined by summing the diagonal elements and dividing by the total number of observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1"></a>ord.test<span class="sc">$</span>pred3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(ord.step, <span class="at">newdata =</span> ord.test, <span class="at">type=</span><span class="st">"class"</span>) </span>
<span id="cb129-2"><a href="#cb129-2"></a>ctable.pred3 <span class="ot">&lt;-</span> <span class="fu">table</span>(ord.test<span class="sc">$</span>fetal_health, ord.test<span class="sc">$</span>pred3) <span class="co"># classification table</span></span>
<span id="cb129-3"><a href="#cb129-3"></a>ctable.pred3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3
  1 317  13   1
  2  30  23   6
  3   3  15  18</code></pre>
</div>
</div>
<p>The accuracy is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1"></a><span class="fu">round</span>((<span class="fu">sum</span>(<span class="fu">diag</span>(ctable.pred3))<span class="sc">/</span><span class="fu">sum</span>(ctable.pred3))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>) <span class="co"># accuracy </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 84.04</code></pre>
</div>
</div>
<p>Calculating precision, recall, and F1-score for each class:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1"></a>precision <span class="ot">&lt;-</span> <span class="fu">diag</span>(ctable.pred3) <span class="sc">/</span> <span class="fu">rowSums</span>(ctable.pred3)</span>
<span id="cb133-2"><a href="#cb133-2"></a>recall <span class="ot">&lt;-</span> <span class="fu">diag</span>(ctable.pred3) <span class="sc">/</span> <span class="fu">colSums</span>(ctable.pred3)</span>
<span id="cb133-3"><a href="#cb133-3"></a>f1_score <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> precision <span class="sc">*</span> recall <span class="sc">/</span> (precision <span class="sc">+</span> recall)</span>
<span id="cb133-4"><a href="#cb133-4"></a></span>
<span id="cb133-5"><a href="#cb133-5"></a><span class="co"># Print the results</span></span>
<span id="cb133-6"><a href="#cb133-6"></a><span class="fu">cat</span>(<span class="st">"Precision for Class 1:"</span>, precision[<span class="dv">1</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Precision for Class 1: 0.9577039 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1"></a><span class="fu">cat</span>(<span class="st">"Precision for Class 2:"</span>, precision[<span class="dv">2</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Precision for Class 2: 0.3898305 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1"></a><span class="fu">cat</span>(<span class="st">"Precision for Class 3:"</span>, precision[<span class="dv">3</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Precision for Class 3: 0.5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1"></a><span class="fu">cat</span>(<span class="st">"Recall for Class 1:"</span>, recall[<span class="dv">1</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recall for Class 1: 0.9057143 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1"></a><span class="fu">cat</span>(<span class="st">"Recall for Class 2:"</span>, recall[<span class="dv">2</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recall for Class 2: 0.4509804 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1"></a><span class="fu">cat</span>(<span class="st">"Recall for Class 3:"</span>, recall[<span class="dv">3</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recall for Class 3: 0.72 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1"></a><span class="fu">cat</span>(<span class="st">"F1-score for Class 1:"</span>, f1_score[<span class="dv">1</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F1-score for Class 1: 0.9309838 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1"></a><span class="fu">cat</span>(<span class="st">"F1-score for Class 2:"</span>, f1_score[<span class="dv">2</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F1-score for Class 2: 0.4181818 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1"></a><span class="fu">cat</span>(<span class="st">"F1-score for Class 3:"</span>, f1_score[<span class="dv">3</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F1-score for Class 3: 0.5901639 </code></pre>
</div>
</div>
<p>In conclusion, the ordinal model demonstrates proficiency in predicting fetal health class 1 (normal). However, its predictive accuracy diminishes notably for classes 2 (suspect) and 3 (pathological), particularly with a lower overall score for class 2 when compared to other binary models. Given that classes 2 and 3 correspond to Suspect and Pathological conditions, accurate prediction in these categories is crucial. Consequently, the ordinal model proves less effective in predicting and classifying fetal health, especially in cases of non-normal fetal health conditions.</p>
<p>Poor performance in predicting class 2 and class3 may be attributed to its low representation in the dataset. Imbalances in class distribution can challenge the model’s ability to learn and generalize effectively for minority classes, influencing overall predictive accuracy.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">7. Conclusion</h2>
<p>Comparing all the models, <strong>[best model]</strong> shows the best performance in predicting fetal health, particularly when focusing on recall.</p>
<p><strong>[Detail of comparsion]</strong></p>
<p>The logistic regression model and the pruned tree model from the CART algorithm exhibit similar performance, with both demonstrating effective predictive capabilities. <strong>[other tree results]</strong></p>
<p>However, the ordinal categorical response model exhibits subpar performance, notably in predicting fetal health statuses categorized as ‘suspect’ and ‘pathological.’ This suboptimal performance could be attributed to the low representation of these classes in the dataset. Consequently, binary models that consolidate classes 2 and 3 might help address the imbalance and prevent the model from being biased toward the majority class. The classes 2 and 3 represent similar conditions and the goal was to distinguish normal from non-normal fetal health, so that combining them could simplify the task for the model.</p>
</section>
<section id="references-and-citation" class="level2">
<h2 class="anchored" data-anchor-id="references-and-citation">8. References and Citation</h2>
<ol type="1">
<li>Ayres de Campos et al.&nbsp;(2000) SisPorto 2.0 A Program for Automated Analysis of Cardiotocograms. J Matern Fetal Med 5:311-318 (<a href="https://onlinelibrary.wiley.com/doi/10.1002/1520-6661(200009/10)9:5%3C311::AID-MFM12%3E3.0.CO;2-9">link</a>)</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>